# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master
- working

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- powershell: |
    Install-Module Pester -Force -MaximumVersion 4.999.999
- powershell: |
    Write-Host $pid
    Import-Module ./codespaces.psm1
    Start-Codespaces -Subscription $env:SUBSCRIPTION_ID -ResourceGroup $env:secrets.RESOURCE_GROUP -Plan $env:secrets.PLAN_ID -ArmToken $env:secrets.ARM_TOKEN
    Invoke-Pester test -EnableExit
