# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master
- working

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- pwsh: |
    Install-Module Pester -Force -MaximumVersion 4.999.999

- pwsh: |
    Write-Host $pid
    Import-Module ./Codespaces.psm1
    Start-Codespaces -Subscription  $env:sub -ResourceGroup $env:res -Plan $env:plan -ArmToken $env:arm
    Invoke-Pester test -EnableExit
    ./TestFile.ps1
  env:
    sub: $(SUBSCRIPTION_ID)
    res: $(RESOURCE_GROUP)
    plan: $(PLAN_ID)
    arm: $(ARM_TOKEN)
