
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- powershell: |
    Install-Module Pester -Force -MaximumVersion 4.999.999
- powershell: |
    Invoke-Pester test -EnableExit
  env:
    sub: $(SUBSCRIPTION_ID)
    res: $(RESOURCE_GROUP)
    plan: $(PLAN_ID)
    arm: $(ARM_TOKEN)
